#!/usr/bin/env python
import os
import optparse


def opts():
    parser = optparse.OptionParser()
    parser.add_option("-l", dest="location", default='currentLocation', help="location for dump file")
    options, args = parser.parse_args()
    return options


def makeCustomizeCards(opt):
    currentLocation = os.getcwd()
    if opt.location == 'currentLocation':
        location = currentLocation
    else:
        location = opt.location
        os.chdir(location)
    print 'In %s' %location

    dirs = os.listdir(location)
    for iDir in dirs:
        lines = open("%s/%s/param_card.dat" %(location, iDir), "r").readlines()
        writeLine = 0
        output = open("%s/%s/customizecards.dat" %(location, iDir), "w")
        output.writelines("# Auto generated by makeCustomizeCards.py\n")
        for iLine in lines:
            if writeLine != 0 and writeLine <= 5:
                output.writelines("set param_card bsm %s" %iLine)
                writeLine += 1
            if "Block bsm" in iLine:
                writeLine = 1
        output.close()
                
options = opts()
makeCustomizeCards(options)
